package mx.ihsa.hibernate.model;
// Generated 19/02/2019 02:54:12 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements java.io.Serializable {

	private int idPerfil;
	private String descPerfil;
	private String observaciones;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Perfil() {
	}

	public Perfil(int idPerfil, String descPerfil) {
		this.idPerfil = idPerfil;
		this.descPerfil = descPerfil;
	}

	public Perfil(int idPerfil, String descPerfil, String observaciones, Set<Usuario> usuarios) {
		this.idPerfil = idPerfil;
		this.descPerfil = descPerfil;
		this.observaciones = observaciones;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "id_perfil", unique = true, nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "desc_perfil", nullable = false, length = 50)
	public String getDescPerfil() {
		return this.descPerfil;
	}

	public void setDescPerfil(String descPerfil) {
		this.descPerfil = descPerfil;
	}

	@Column(name = "observaciones", length = 50)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
