package mx.ihsa.hibernate.model;
// Generated 19/02/2019 02:54:12 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name = "tipomovimiento", schema = "public")
public class Tipomovimiento implements java.io.Serializable {

	private int idTipMov;
	private String descTipMov;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Tipomovimiento() {
	}

	public Tipomovimiento(int idTipMov) {
		this.idTipMov = idTipMov;
	}

	public Tipomovimiento(int idTipMov, String descTipMov, Set<Movimiento> movimientos) {
		this.idTipMov = idTipMov;
		this.descTipMov = descTipMov;
		this.movimientos = movimientos;
	}

	@Id

	@Column(name = "id_tip_mov", unique = true, nullable = false)
	public int getIdTipMov() {
		return this.idTipMov;
	}

	public void setIdTipMov(int idTipMov) {
		this.idTipMov = idTipMov;
	}

	@Column(name = "desc_tip_mov", length = 50)
	public String getDescTipMov() {
		return this.descTipMov;
	}

	public void setDescTipMov(String descTipMov) {
		this.descTipMov = descTipMov;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomovimiento")
	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
